"""Shared constants for XY SecBoot host tools."""

from __future__ import annotations

MANIFEST_MAGIC = 0x54425358  # 'XSBT'
MANIFEST_VERSION = 1
MANIFEST_SIZE = 268
MANIFEST_SIGNED_LEN = 136
PRODUCT_ID_N32 = 0x00010001
IMAGE_TYPE_APP = 0

PACKAGE_MAGIC = b"XSBP"
PACKAGE_VERSION = 1
PACKAGE_HEADER_SIZE = 24

SUITE_MARKET = 3

UART_MAGIC = b"SB"
UART_VERSION = 1
UART_HEADER_SIZE = 20
UART_ACK_SIZE = 12
UART_DEFAULT_PAYLOAD = 256

APP_IMAGE_ADDR_N32 = 0x08007800
APP_MANIFEST_ADDR_N32 = 0x08007000
APP_IMAGE_SIZE_N32 = 0x00016800


class PacketType:
    HELLO = 1
    CAPS = 2
    MANIFEST = 3
    DATA = 4
    END = 5
    ACK = 6
    NACK = 7
    ERROR = 8
    RESET = 9
    ABORT = 10


class Reason:
    OK = 0
    BAD_HEADER_CRC = 1
    BAD_PAYLOAD_CRC = 2
    BAD_SEQ = 3
    BAD_OFFSET = 4
    BAD_LENGTH = 5
    BAD_MANIFEST = 6
    FLASH_ERASE_FAILED = 7
    FLASH_WRITE_FAILED = 8
    FLASH_VERIFY_FAILED = 9
    IMAGE_VERIFY_FAILED = 10
    ROLLBACK_REJECTED = 11
    BUSY = 12


PACKET_NAMES = {
    PacketType.HELLO: "HELLO",
    PacketType.CAPS: "CAPS",
    PacketType.MANIFEST: "MANIFEST",
    PacketType.DATA: "DATA",
    PacketType.END: "END",
    PacketType.ACK: "ACK",
    PacketType.NACK: "NACK",
    PacketType.ERROR: "ERROR",
    PacketType.RESET: "RESET",
    PacketType.ABORT: "ABORT",
}

REASON_NAMES = {
    Reason.OK: "OK",
    Reason.BAD_HEADER_CRC: "BAD_HEADER_CRC",
    Reason.BAD_PAYLOAD_CRC: "BAD_PAYLOAD_CRC",
    Reason.BAD_SEQ: "BAD_SEQ",
    Reason.BAD_OFFSET: "BAD_OFFSET",
    Reason.BAD_LENGTH: "BAD_LENGTH",
    Reason.BAD_MANIFEST: "BAD_MANIFEST",
    Reason.FLASH_ERASE_FAILED: "FLASH_ERASE_FAILED",
    Reason.FLASH_WRITE_FAILED: "FLASH_WRITE_FAILED",
    Reason.FLASH_VERIFY_FAILED: "FLASH_VERIFY_FAILED",
    Reason.IMAGE_VERIFY_FAILED: "IMAGE_VERIFY_FAILED",
    Reason.ROLLBACK_REJECTED: "ROLLBACK_REJECTED",
    Reason.BUSY: "BUSY",
}
